export const rate_22423 =
[
    {
        "id": 22423,
        "is_visible": 1,
        "on_date": "2024-04-29",
        "key_orig": "046570c722a621a9730e579e295f30d3",
        "title": "Ningbo - Владивосток - Москва(Тучково) (40'HC)",
        "transporter_name": "Hub-Shipping, Трамис",
        "charterer_name": "Трамис",
        "unit_type": 8,
        "unit_code": "40'HC",
        "base_place_from": 2,
        "base_place_from_name": "Ningbo",
        "base_place_to": 72,
        "base_place_to_name": "Москва",
        "port_id": 214,
        "port_name": "Владивосток",
        "terminal_id": 4561,
        "terminal_name": "ВСК",
        "station_id": 72,
        "station_name": "Москва",
        "line_id": 11948,
        "line_name": "Hub-Shipping",
        "place_across_id": 214,
        "is_fareast_region": 1,
        "is_south_region": 0,
        "is_northwest_region": 0,
        "place_across_name": "Владивосток",
        "delivery_term_id": 6,
        "delivery_term_code": "FOB",
        "rmb_rate": 12.7602,
        "end_date": "2024-07-31",
        "is_gondola": 1,
        "raiting": 45.0,
        "is_schedule": 1,
        "is_prebook": 0,
        "is_unverified": 0,
        "total": 234000,
        "rmb_total": 18400,
        "tranzit_time": 35,
        "all_time": 44,
        "full_summa": 0.00000000000000000000,
        "sec_summa": 7508,
        "is_alarm": 0,
        "alarm_class": "",
        "all_comment": "",
        "inside_comment": "",
        "across_place_name_ext": "ВСК",
        "across_place_name": "Владивосток",
        "across_place_name_ext_id": "4561",
        "across_place_name_id": "214",
        "base_place_from_name_ext": "Ningbo",
        "is_direct": 0,
        "is_ete": 0,
        "is_sea": 1,
        "date_to": "2024-04-30",
        "cbr_rate": 92.4155,
        "average_loading_time": 0,
        "usd_total": 2532,
        "is_trash": false,
        "is_soc": 0,
        "landlord_id": null,
        "landlord_name": "",
        "lack_of_empty_equipment_date": null,
        "lack_of_empty_equipment_img": "",
        "is_lack_of_empty_equipment_date": false,
        "lack_of_empty_equipment_type": 0,
        "is_lack_of_empty_equipment_date_desc": "",
        "zd_station_id": "4020",
        "zd_satation_name": "Тучково",
        "is_hot": 0,
        "is_inside": 0,
        "is_agent": 0,
        "is_backstage": 0,
        "is_not_vtt": 0,
        "is_nak": 0,
        "is_hide_line": 0,
        "client_id": 0,
        "client_name": "",
        "is_convention": 0,
        "convention_date_to": null,
        "freight_id": 1835221,
        "detail": [
            {
                "id": "22423_215",
                "cost": 2000,
                "icon": "1.png",
                "summa": 1390,
                "service": "Море",
                "type_id": 215,
                "cbr_rate": 92.4155,
                "cur_code": "USD",
                "eq_price": 2000,
                "place_to": "Владивосток",
                "rmb_price": 160,
                "sec_summa": 0,
                "place_from": "Ningbo",
                "service_id": 1,
                "place_to_id": 214,
                "ext_place_to": "ВСК",
                "tranzit_time": 31,
                "place_from_id": 2,
                "charterer_name": "Трамис",
                "condition_name": "На дату выхода судна",
                "ext_place_from": "Ningbo",
                "transporter_name": "Hub-Shipping"
            },
            {
                "id": "22423_214",
                "cost": 230000,
                "icon": "2.png",
                "summa": 2490,
                "service": "ЖД",
                "type_id": 214,
                "cbr_rate": 92.4155,
                "cur_code": "USD",
                "eq_price": 230000,
                "place_to": "Москва",
                "rmb_price": 18030,
                "sec_summa": 7508,
                "place_from": "Владивосток",
                "service_id": 2,
                "place_to_id": 72,
                "ext_place_to": "Тучково",
                "tranzit_time": 31,
                "place_from_id": 214,
                "charterer_name": "Трамис",
                "condition_name": "На дату закрытия склада и передачи контейнера на ж/д",
                "ext_place_from": "ВСК",
                "transporter_name": "Трамис"
            },
            {
                "id": "22423_259",
                "cost": 2000,
                "icon": "3.png",
                "summa": 1050,
                "service": "Drop Off",
                "type_id": 259,
                "cbr_rate": 92.4155,
                "cur_code": "USD",
                "eq_price": 2000,
                "place_to": "Москва",
                "rmb_price": 160,
                "sec_summa": 0,
                "place_from": "Москва",
                "service_id": 4,
                "place_to_id": 72,
                "ext_place_to": "",
                "tranzit_time": 31,
                "place_from_id": 72,
                "charterer_name": "Трамис",
                "condition_name": null,
                "ext_place_from": "Москва",
                "transporter_name": "Hub-Shipping"
            }
        ],
        "client_list": [

        ]
    }
]